sudo: required

language: java
jdk:
  - oraclejdk8

services:
  - docker

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t glnds/zoufzouf .
  - docker push glnds/zoufzouf:0.1

notifications:
  slack:
    secure: zXyYS3fCriAjs6z5oOwqq4em9kalFrB05h9OZ7BTeYV2jvzuet7JVIBM+p4BN72Kfjtcd6UNd7/XPq6Js7QBV7UL1nETihKCaEnzfS/E8PrvHcZzR7L9ko4rWOlYJi6XyxBqeU8WPtvNKG5CBrdACj9PQk6EKYbes88CviKn0uf7403HxbsxYiqZA06d+wr3CuL+G5j1MCcNj/rRrrPmxNw5frvb7lNyKzV5IJUnfsNrnJLjQzU5/5XUlTSsPR4Xd7Xbo/m4nM9jZoURGaAp45L4EsMpbGk1RAJCS0C4v9/Kx1xzf+V/W959ii/vI8/O06RX+D01rfOJDqvD4B2Sv8owvihXU01Ui+TgWpxucFs84LYTJVEFWnICW5m8pKDrEyet3N3xYV/PHQ1rEGHsE8ZsVXlaJdDSH1IME6PV0xWggYHazw+0WHIAR98RAGEgoO4Joaf5fLn81eZcOI5KMcIWuveVTwmGO43XyaDPJ+qlpTh7cvIukxYW+sfurWRSPQc2db06dK6oP9lBtxLne/UNXpLV8zbR7qSwg0lsS8fgWWEjPbfhmzRpGkp7bXr9mC9F9l22NNeUBowV88NTOtvn/QAe4G0dkdznwF9ZdqJ0jJw7sDG8BS9Wmi0uA0QXNVnk9Y/DZTbInV9cEeUCNKlj62eBpt8CAA78rutBSMA=
