version: "0.2-SNAPSHOT-{build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble

test_script:
  - gradlew.bat check

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true

notifications:
  - provider: Slack
    incoming_webhook:
      secure: https://hooks.slack.com/services/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
